# Generated by Django 4.1.3 on 2022-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectotfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectotfm',
            name='imagen',
            field=models.ImageField(upload_to='proyectotfm'),
        ),
    ]
