# Generated by Django 4.1.3 on 2022-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('best_book_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('books_count', models.IntegerField()),
                ('isbn', models.CharField(max_length=255)),
                ('isbn13', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=1000)),
                ('original_publication_year', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=255)),
                ('average_rating', models.CharField(max_length=255)),
                ('ratings_count', models.IntegerField()),
                ('work_ratings_count', models.IntegerField()),
                ('work_text_reviews_count', models.IntegerField()),
                ('ratings_1', models.IntegerField()),
                ('ratings_2', models.IntegerField()),
                ('ratings_3', models.IntegerField()),
                ('ratings_4', models.IntegerField()),
                ('ratings_5', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('small_image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
