# Generated by Django 4.1.3 on 2022-12-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlibros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectotfm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.IntegerField()),
                ('small_image_url', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
